project:
  type: website
  output-dir: docs
  resources:
    - info526-f23-syllabus.pdf

website:
  page-navigation: true
  title: "INFO 526"
  description: "Homepage for INFO 526 - Data Visualization and Analysis at The University of Arizona, Fall 2023."
  site-url: "http://datavizaz.org/"
  favicon: /images/logo.png

  repo-url: https://github.com/INFO526-DataViz
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#378DBD" # Oasis
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/INFO526-DataViz
        text: "GitHub organization"
      - icon: code-square
        href: https://posit.cloud/
        text: "Posit Cloud"
      - icon: person-fill
        text: "D2L"
        href: https://d2l.arizona.edu/d2l/home/1334576
        menu:
          - text: Announcements
            href: https://datavizaz.slack.com
          - text: Zoom meetings
            href: https://arizona.zoom.us/my/gregchism
          - text: Gradebook
            href: https://d2l.arizona.edu/d2l/home/1334576

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Computing"
        contents:
          - href: computing/computing-troubleshooting.qmd
            text: Troubleshooting
          - href: computing/computing-cheatsheets.qmd
            text: Cheatsheets
          - href: computing/computing-git.qmd
            text: Setting up Git
      - section: "Projects"
        contents:
          - href: project/project-1.qmd
            text: Project 1
          - href: student-work/project-1.qmd
            text: Project 1 Examples
          - href: project/project-2.qmd
            text: Project 2
          - href: project/project-tips-resources.qmd
            text: Tips & Resources
      - section: "HW"
        contents:
          - text: HW 01
            href: https://github.com/INFO526-DataViz/hw-01
          - text: HW 02
            href: https://github.com/INFO526-DataViz/hw-02
          - text: HW 03
            href: https://github.com/INFO526-DataViz/hw-03
          - text: HW 04
            href: https://github.com/INFO526-DataViz/hw-04
          - text: HW 05
            href: https://github.com/INFO526-DataViz/hw-05
          - text: HW 06
            href: https://github.com/INFO526-DataViz/hw-06
      - section: "Student work"
        contents:
          - href: student-work/ugly-plot.qmd
            text: Ugly plots
          - href: student-work/thank-you.qmd
            text: Thank you cards
          - href: student-work/project-1.qmd
            text: Project 1 Examples
          

  page-footer:
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Greg Chism"
    background: "#378DBD" # Oasis

format:
  html:
    theme:
      light: [cosmo, style/info526.scss]
      dark: [cosmo, style/info526.scss, style/dark.scss]
    linkcolor: "#EF4056" # Azurite
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Montserrat"

execute:
  freeze: auto

editor: visual
